os: linux

jobs:
  include:
    - script: echo "Running unit tests (1)"
    - stage: GitHub Release
      script: ./autogen.sh
      script: make 
      #deploy:
      #    provider: releases
      #    api_key: "$GITHUB_OAUTH_TOKEN"
      #    skip_cleanup: true
      #    on:
      #      tags: true